# Generated by Django 2.2 on 2019-05-20 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authprofile',
            name='birthday',
            field=models.DateField(auto_now_add=True, verbose_name='生日'),
        ),
        migrations.AlterField(
            model_name='authprofile',
            name='sex',
            field=models.CharField(choices=[(1, 'girl'), (2, 'boy')], default=2, max_length=4, verbose_name='性别'),
        ),
        migrations.AlterField(
            model_name='authprofile',
            name='user_ico',
            field=models.ImageField(default='ico/default.jpg', upload_to='ico/%Y/%m/%d', verbose_name='用户头像'),
        ),
    ]
