# Generated by Django 2.2 on 2019-05-22 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20190520_1613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authprofile',
            name='birthday',
            field=models.DateField(default='2019-05-20', verbose_name='生日'),
        ),
        migrations.AlterField(
            model_name='authprofile',
            name='sex',
            field=models.BooleanField(choices=[(0, 'girl'), (1, 'boy')], default=1, verbose_name='性别'),
        ),
    ]
