# Generated by Django 2.2 on 2019-05-26 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20190522_1645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authprofile',
            name='user_ico',
            field=models.ImageField(blank=True, default='ico/default.jpg', upload_to='ico/%Y/%m/%d', verbose_name='用户头像'),
        ),
    ]
