# Generated by Django 2.2 on 2019-05-22 16:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='书名')),
                ('author', models.CharField(max_length=10, verbose_name='作者')),
                ('summary', models.CharField(max_length=100, verbose_name='摘要')),
                ('publish', models.CharField(max_length=50, verbose_name='出版社')),
                ('free', models.BooleanField(choices=[(1, '免费'), (0, '收费')], default=1, verbose_name='是否免费')),
                ('tag', models.CharField(choices=[('Python', 'Python相关书籍'), ('linux', 'linux相关书籍'), ('Java', 'Java相关书籍'), ('Redis', 'Redis相关书籍'), ('Mysql', 'Mysql相关书籍'), ('Docker', 'Docker相关书籍'), ('Html_css_javascript', 'html+css+javascript相关书籍')], max_length=10, verbose_name='书籍类型')),
                ('test_read', models.TextField(verbose_name='试读部分')),
                ('collect_user', models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='收藏者')),
            ],
            options={
                'verbose_name': '书籍',
                'verbose_name_plural': '书籍',
            },
        ),
    ]
