# Generated by Django 2.2 on 2019-05-22 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_auto_20190522_1649'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='book_cover',
            field=models.ImageField(default='cover/default.jpg', upload_to='cover/%Y/%m/%d', verbose_name='封面'),
        ),
        migrations.AddField(
            model_name='book',
            name='book_file',
            field=models.FileField(default='file/default.txt', upload_to='file/%Y/%m/%d', verbose_name='书籍主体'),
        ),
        migrations.AlterField(
            model_name='book',
            name='name',
            field=models.CharField(db_index=True, max_length=50, unique=True, verbose_name='书名'),
        ),
    ]
