# Generated by Django 2.2 on 2019-05-24 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_auto_20190522_1719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='tag',
            field=models.CharField(choices=[('Python', 'Python相关书籍'), ('linux', 'linux相关书籍'), ('Java', 'Java相关书籍'), ('Redis', 'Redis相关书籍'), ('Mysql', 'Mysql相关书籍'), ('Docker', 'Docker相关书籍'), ('Html_css_javascript', 'html+css+javascript相关书籍')], db_index=True, max_length=20, verbose_name='书籍类型'),
        ),
    ]
