# Generated by Django 2.2 on 2019-05-26 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_auto_20190524_1829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_cover',
            field=models.ImageField(blank=True, default='cover/default.jpg', upload_to='cover/%Y/%m/%d', verbose_name='封面'),
        ),
    ]
