# Generated by Django 2.2 on 2019-05-26 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_auto_20190526_1640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_file',
            field=models.FileField(blank=True, default='file/default.txt', upload_to='file/%Y/%m/%d', verbose_name='书籍主体'),
        ),
    ]
