# Generated by Django 2.2 on 2019-05-27 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0007_auto_20190526_2313'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='collect_num',
            field=models.IntegerField(default=0, verbose_name='收藏数'),
        ),
    ]
